services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M

  web:
    build: .
    ports:
      - "8015:80"
    security_opt:
      - no-new-privileges:true
    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD}
